//gpt generated user dataset for initial dev

export const userinfo = [
    {
      id: "1",
      first_name: "John",
      last_name: "Doe",
      age: 28,
      email: "john.doe@example.com",
      web: "www.johndoe.com",
      company_name: "Doe Enterprises",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    {
      id: "2",
      first_name: "Jane",
      last_name: "Smith",
      age: 34,
      email: "jane.smith@example.com",
      web: "www.janesmith.com",
      company_name: "Smith Solutions",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    {
      id: "3",
      first_name: "Michael",
      last_name: "Johnson",
      age: 42,
      email: "michael.johnson@example.com",
      web: "www.michaeljohnson.com",
      company_name: "Johnson & Co",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    {
      id: "4",
      first_name: "Emily",
      last_name: "Davis",
      age: 29,
      email: "emily.davis@example.com",
      web: "www.emilydavis.com",
      company_name: "Davis Design",
      city: "Houston",
      state: "TX",
      zip: "77001",
    },
    {
      id: "5",
      first_name: "William",
      last_name: "Brown",
      age: 36,
      email: "william.brown@example.com",
      web: "www.williambrown.com",
      company_name: "Brown Industries",
      city: "Phoenix",
      state: "AZ",
      zip: "85001",
    },
    {
      id: "6",
      first_name: "Olivia",
      last_name: "Martinez",
      age: 31,
      email: "olivia.martinez@example.com",
      web: "www.oliviamartinez.com",
      company_name: "Martinez Marketing",
      city: "Philadelphia",
      state: "PA",
      zip: "19101",
    },
    {
      id: "7",
      first_name: "James",
      last_name: "Taylor",
      age: 45,
      email: "james.taylor@example.com",
      web: "www.jamestaylor.com",
      company_name: "Taylor Technologies",
      city: "San Antonio",
      state: "TX",
      zip: "78201",
    },
    {
      id: "8",
      first_name: "Sophia",
      last_name: "Anderson",
      age: 27,
      email: "sophia.anderson@example.com",
      web: "www.sophiaanderson.com",
      company_name: "Anderson Consulting",
      city: "San Diego",
      state: "CA",
      zip: "92101",
    },
    {
      id: "9",
      first_name: "Benjamin",
      last_name: "Thomas",
      age: 38,
      email: "benjamin.thomas@example.com",
      web: "www.benjaminthomas.com",
      company_name: "Thomas Enterprises",
      city: "Dallas",
      state: "TX",
      zip: "75201",
    },
    {
      id: "10",
      first_name: "Ava",
      last_name: "Jackson",
      age: 33,
      email: "ava.jackson@example.com",
      web: "www.avajackson.com",
      company_name: "Jackson Design",
      city: "San Jose",
      state: "CA",
      zip: "95101",
    },
    {
      id: "11",
      first_name: "Charlotte",
      last_name: "Wilson",
      age: 30,
      email: "charlotte.wilson@example.com",
      web: "www.charlottewilson.com",
      company_name: "Wilson Tech",
      city: "Austin",
      state: "TX",
      zip: "73301",
    },
    {
      id: "12",
      first_name: "Ethan",
      last_name: "Moore",
      age: 35,
      email: "ethan.moore@example.com",
      web: "www.ethanmoore.com",
      company_name: "Moore Designs",
      city: "San Francisco",
      state: "CA",
      zip: "94101",
    },
    {
      id: "13",
      first_name: "Amelia",
      last_name: "Harris",
      age: 32,
      email: "amelia.harris@example.com",
      web: "www.ameliaharris.com",
      company_name: "Harris Group",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    {
      id: "14",
      first_name: "Liam",
      last_name: "Martin",
      age: 29,
      email: "liam.martin@example.com",
      web: "www.liammartin.com",
      company_name: "Martin & Co",
      city: "Denver",
      state: "CO",
      zip: "80201",
    },
    {
      id: "15",
      first_name: "Mia",
      last_name: "Martinez",
      age: 28,
      email: "mia.martinez@example.com",
      web: "www.miamartinez.com",
      company_name: "Martinez Enterprises",
      city: "Miami",
      state: "FL",
      zip: "33101",
    },
    {
      id: "16",
      first_name: "Noah",
      last_name: "Clark",
      age: 40,
      email: "noah.clark@example.com",
      web: "www.noahclark.com",
      company_name: "Clark Innovations",
      city: "Boston",
      state: "MA",
      zip: "02101",
    },
    {
      id: "17",
      first_name: "Isabella",
      last_name: "Lewis",
      age: 37,
      email: "isabella.lewis@example.com",
      web: "www.isabellalewis.com",
      company_name: "Lewis Solutions",
      city: "Baltimore",
      state: "MD",
      zip: "21201",
    },
    {
      id: "18",
      first_name: "Lucas",
      last_name: "Walker",
      age: 45,
      email: "lucas.walker@example.com",
      web: "www.lucaswalker.com",
      company_name: "Walker Technologies",
      city: "Las Vegas",
      state: "NV",
      zip: "89101",
    },
    {
      id: "19",
      first_name: "Aiden",
      last_name: "Robinson",
      age: 33,
      email: "aiden.robinson@example.com",
      web: "www.aidenrobinson.com",
      company_name: "Robinson Corp",
      city: "Portland",
      state: "OR",
      zip: "97201",
    },
    {
      id: "20",
      first_name: "Ella",
      last_name: "Young",
      age: 31,
      email: "ella.young@example.com",
      web: "www.ellayoung.com",
      company_name: "Young Innovations",
      city: "Atlanta",
      state: "GA",
      zip: "30301",
    },
    {
      id: "21",
      first_name: "Henry",
      last_name: "King",
      age: 39,
      email: "henry.king@example.com",
      web: "www.henryking.com",
      company_name: "King Enterprises",
      city: "Charlotte",
      state: "NC",
      zip: "28201",
    },
    {
      id: "22",
      first_name: "Avery",
      last_name: "Scott",
      age: 27,
      email: "avery.scott@example.com",
      web: "www.averyscott.com",
      company_name: "Scott & Associates",
      city: "Detroit",
      state: "MI",
      zip: "48201",
    },
    {
      id: "23",
      first_name: "Daniel",
      last_name: "Green",
      age: 36,
      email: "daniel.green@example.com",
      web: "www.danielgreen.com",
      company_name: "Green Solutions",
      city: "Memphis",
      state: "TN",
      zip: "37501",
    },
    {
      id: "24",
      first_name: "Harper",
      last_name: "Baker",
      age: 34,
      email: "harper.baker@example.com",
      web: "www.harperbaker.com",
      company_name: "Baker Designs",
      city: "Nashville",
      state: "TN",
      zip: "37201",
    },
    {
      id: "25",
      first_name: "Matthew",
      last_name: "Perez",
      age: 32,
      email: "matthew.perez@example.com",
      web: "www.matthewperez.com",
      company_name: "Perez & Co",
      city: "Louisville",
      state: "KY",
      zip: "40201",
    },
    {
      id: "26",
      first_name: "Abigail",
      last_name: "Carter",
      age: 30,
      email: "abigail.carter@example.com",
      web: "www.abigailcarter.com",
      company_name: "Carter Consulting",
      city: "Milwaukee",
      state: "WI",
      zip: "53201",
    },
    {
      id: "27",
      first_name: "Sebastian",
      last_name: "Turner",
      age: 41,
      email: "sebastian.turner@example.com",
      web: "www.sebastianturner.com",
      company_name: "Turner Enterprises",
      city: "Albuquerque",
      state: "NM",
      zip: "87101",
    },
    {
      id: "28",
      first_name: "Mila",
      last_name: "Phillips",
      age: 35,
      email: "mila.phillips@example.com",
      web: "www.milaphillips.com",
      company_name: "Phillips Group",
      city: "Fresno",
      state: "CA",
      zip: "93701",
    },
    {
      id: "29",
      first_name: "Alexander",
      last_name: "Evans",
      age: 29,
      email: "alexander.evans@example.com",
      web: "www.alexanderevans.com",
      company_name: "Evans Solutions",
      city: "Sacramento",
      state: "CA",
      zip: "94203",
    },
    {
      id: "30",
      first_name: "Evelyn",
      last_name: "Nelson",
      age: 33,
      email: "evelyn.nelson@example.com",
      web: "www.evelynnelson.com",
      company_name: "Nelson Innovations",
      city: "Kansas City",
      state: "MO",
      zip: "64101",
    },
  ];
  